---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: tools-linkebroken-{{ .Values.release }}
  namespace: {{ .Values.namespace }}
  labels:
    app: tools-linkebroken
    release: {{ .Values.release }}
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    app: tools-linkebroken
    release: {{ .Values.release }}
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: tools-linkebroken
        release: {{ .Values.release }}
    spec:
      containers:
      - name: nodejs
        image: docker-registry.default.svc:5000/{{ .Values.image.namespace }}/tools-linkebroken:{{ .Values.image.version }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 200Mi
  triggers: []
